M48
; DRILL file {KiCad 6.0.2+dfsg-1} date za 03 sep 2022 15:09:45
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-03T15:09:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.6545Y-2.7244
X4.8455Y-2.7244
T2
X4.6427Y-2.6051
X4.8573Y-2.6051
T0
M30
